
carre1:	main1.cpp
	g++ -std=c++11  -O2 -g -o carre1.exe main1.cpp  -lm

carre2:	main2.cpp
	g++ -std=c++11  -O2 -g -o carre2.exe main2.cpp  -lm

carre3:	main3.cpp
	g++ -std=c++11  -O2 -g -o carre3.exe main3.cpp  -lm

carre4:	main4.cpp
	g++ -std=c++11  -O2 -g -o carre4.exe main4.cpp  -lm

carre5:	main5.cpp
	g++ -std=c++11  -O2 -g -o carre5.exe main5.cpp  -lm





texte1:	texte1.cpp
	g++ -std=c++11  -O2 -g -o texte1.exe texte1.cpp  -lm

texte2:	texte2.cpp
	g++ -std=c++11  -O2 -g -o texte2.exe texte2.cpp  -lm

texte3:	texte3.cpp
	g++ -std=c++11  -O2 -g -o texte3.exe texte3.cpp  -lm

texte4:	texte4.cpp
	g++ -std=c++11  -O2 -g -o texte4.exe texte4.cpp  -lm


clean:	
	rm *.exe

